import type { OnboardingSuggestedRecurrent } from "./types";

export const SUGGESTED_RECURRENTS: OnboardingSuggestedRecurrent[] = [
  {
    id: "sug_salary",
    labelKey: "onboarding.recurrents.salary",
    label_es: "Nómina",
    label_en: "Salary",
    type: "income",
    suggestedCategoryName: "Nómina",
    placeholderAmount: "2000",
    frequency: "monthly",
    interval: 1,
    icon: "💼",
  },
  {
    id: "sug_rent",
    labelKey: "onboarding.recurrents.rent",
    label_es: "Alquiler",
    label_en: "Rent",
    type: "expense",
    suggestedCategoryName: "Hogar",
    placeholderAmount: "850",
    frequency: "monthly",
    interval: 1,
    icon: "🏠",
  },
  {
    id: "sug_netflix",
    labelKey: "onboarding.recurrents.netflix",
    label_es: "Netflix",
    label_en: "Netflix",
    type: "expense",
    suggestedCategoryName: "Suscripciones",
    placeholderAmount: "17.99",
    frequency: "monthly",
    interval: 1,
    icon: "📺",
  },
  {
    id: "sug_spotify",
    labelKey: "onboarding.recurrents.spotify",
    label_es: "Spotify",
    label_en: "Spotify",
    type: "expense",
    suggestedCategoryName: "Suscripciones",
    placeholderAmount: "10.99",
    frequency: "monthly",
    interval: 1,
    icon: "🎵",
  },
  {
    id: "sug_gym",
    labelKey: "onboarding.recurrents.gym",
    label_es: "Gimnasio",
    label_en: "Gym",
    type: "expense",
    suggestedCategoryName: "Salud",
    placeholderAmount: "39.90",
    frequency: "monthly",
    interval: 1,
    icon: "💪",
  },
  {
    id: "sug_phone",
    labelKey: "onboarding.recurrents.phone",
    label_es: "Teléfono",
    label_en: "Phone",
    type: "expense",
    suggestedCategoryName: "Suministros",
    placeholderAmount: "25",
    frequency: "monthly",
    interval: 1,
    icon: "📱",
  },
];

export const ONBOARDING_MIN_RECURRENTS = 2;

export const GOAL_TIMELINE_OPTIONS = [3, 6, 12] as const;
