export const themeTokens = {
  light: {
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
    radii: {
      sm: 6,
      md: 10,
      lg: 16,
      pill: 999,
    },
    typography: {
      size: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 22,
        display: 28,
      },
      weight: {
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    colors: {
      bg: {
        primary: "#FAFAF8",
        secondary: "#F7F8FA",
        surface: "#FFFFFF",
      },
      text: {
        primary: "#1C1E21",
        secondary: "#5F6368",
        muted: "#9AA0A6",
      },
      action: {
        primary: "#5B8DFF",
        secondary: "#E8EEFF",
        disabled: "#C7D2FE",
      },
      state: {
        positive: "#22A06B",
        negative: "#DE350B",
        warning: "#E8B45C",
        neutral: "#DADCE0",
      },
      shadow: {
        soft: "#0000001A",
      },
    },
  },
  dark: {
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
    radii: {
      sm: 6,
      md: 10,
      lg: 16,
      pill: 999,
    },
    typography: {
      size: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 22,
        display: 28,
      },
      weight: {
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    colors: {
      bg: {
        primary: "#0E0F12",
        secondary: "#15171C",
        surface: "#1C1F26",
      },
      text: {
        primary: "#F1F3F4",
        secondary: "#B0B3B8",
        muted: "#7A7D81",
      },
      action: {
        primary: "#FFFFFF",
        secondary: "#2A2D34",
        disabled: "#3A3D44",
      },
      state: {
        positive: "#22A06B",
        negative: "#DE350B",
        warning: "#D9A957",
        neutral: "#2A2D34",
      },
      shadow: {
        soft: "#00000033",
      },
    },
  },
} as const;

export const accountRedesignTokens = {
  colors: {
    bg: "#FAFAF8",
    surface: "#FFFFFF",
    surfaceAlt: "#F5F4F0",
    border: "#E8E6E1",
    borderLight: "#F0EEE9",
    textPrimary: "#1A1A18",
    textSecondary: "#6B6B65",
    textTertiary: "#9C9C95",
    income: "#1B7A4A",
    incomeBg: "#E8F5EE",
    incomeLight: "#D0EBDD",
    expense: "#C4441A",
    expenseBg: "#FDF0EB",
    expenseLight: "#F9DDD2",
    accent: "#2563EB",
    accentBg: "#EFF4FF",
    category: {
      casa: "#FEF3C7",
      familia: "#FCE7F3",
      ocio: "#E0E7FF",
      restaurantes: "#FFEDD5",
      interests: "#D1FAE5",
      lottery: "#EDE9FE",
      default: "#F3F4F6",
    },
  },
  typography: {
    family: {
      sans: "DMSans",
      sansMedium: "DMSans-Medium",
      sansSemiBold: "DMSans-SemiBold",
      sansBold: "DMSans-Bold",
      mono: "JetBrainsMono",
      monoMedium: "JetBrainsMono-Medium",
    },
    size: {
      xs: 10,
      sm: 11,
      base: 12,
      md: 13,
      lg: 14,
      xl: 16,
      "2xl": 18,
      "3xl": 24,
      "4xl": 36,
    },
    lineHeight: {
      tight: 1.1,
      normal: 1.4,
      relaxed: 1.6,
    },
  },
  spacing: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    "2xl": 14,
    "3xl": 16,
    "4xl": 20,
    "5xl": 24,
    "6xl": 32,
  },
  radii: {
    sm: 8,
    md: 10,
    lg: 14,
    xl: 20,
    full: 100,
  },
  shadows: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
  },
} as const;

export const onboardingTokens = {
  colors: {
    dark: "#1A1F36",
    darkHover: "#2A3050",
    bg: "#FAFAF8",
    border: "#E5E7EB",
    text: "#1A1F36",
    textSecondary: "#6B7280",
    textMuted: "#9CA3AF",
    green: "#16A34A",
    greenBg: "#F0FDF4",
    greenBorder: "#BBF7D0",
    red: "#DC2626",
    amber: "#F59E0B",
    blue: "#3B82F6",
    blueBg: "#EFF6FF",
    blueBorder: "#BFDBFE",
    white: "#FFFFFF",
  },
  radii: {
    lg: 16,
    md: 12,
    sm: 8,
  },
} as const;

export const movementsTokens = {
  colors: {
    bg: "#FAFAF8",
    surface: "#FFFFFF",
    border: "#F0F0F0",
    borderStrong: "#E5E5E5",
    textPrimary: "#1A1A1A",
    textSecondary: "#6B6B6B",
    textTertiary: "#9B9B9B",
    incomeGreen: "#22A06B",
    incomeGreenBg: "#E6F9F0",
    incomeSolid: "#6ABB7B",
    incomePending: "#C8E6CD",
    expenseRed: "#DE350B",
    expenseRedBg: "#FFF0E6",
    expenseSolid: "#E07A68",
    expensePending: "#F8D7CF",
    pendingAmber: "#E2850A",
    pendingAmberBg: "#FFF8E6",
    pendingAmberBorder: "#F5D990",
    recurrentPurple: "#7C5CFC",
    recurrentPurpleBg: "#F3F0FF",
    recurrentPurpleBorder: "#D4CCFF",
    accentBlue: "#0065FF",
    accentBlueBg: "#E6F0FF",
    chipBg: "#F5F5F5",
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 999,
  },
  typography: {
    fontFamily: "DMSans",
    sizes: {
      xs: 11,
      sm: 12,
      base: 13,
      md: 14,
      lg: 15,
      xl: 20,
      "2xl": 24,
    },
    weights: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
  },
} as const;

export type ThemeTokens = typeof themeTokens.light;
